Allow TransactionOutbox#scheduler ThreadFactory customization
gruelbox/transaction-outbox pull request #688
Opened 2024-08-12 14:00 UTC by reda-alaoui

2024-08-21 20:01 UTC, badgerwithagun commented
I think this would be more neatly solved by as noted on #687 by allowing a `ScheduledExecutorService` to be supplied when building the `TransactionOutbox`.  You should have the option to be entirely control of your executor lifetimes rather than expecting the outbox to do it.

2024-08-21 20:30 UTC, reda-alaoui commented
@badgerwithagun , by default, `ExecutorSubmitter` uses a single thread pool. I thought this was important to keep this number of threads to avoid potential concurrency issues. Letting applications pass a full executor instead of a `ThreadFactory` will allow the formers to provide multi threaded executors. 

If you think there is no concurrency issue with an executor holding more than 1 thread, we could consider there is resource waste issue and/or an API surface that is too wide if 1 thread is strictly enough.

Let me know what you think of that :)

2024-08-26 09:19 UTC, badgerwithagun commented
@reda-alaoui  I'm fine with the JAvadoc just making it clear that the `Executor` should only have one executing thread and queue concurrent requests.  By default it will use the existing implementation which works fine. If a user starts messing around with it, they should know what they are doing!

2024-08-26 09:43 UTC, badgerwithagun requested changes
.

2025-05-24 10:14 UTC, badgerwithagun commented
Closing due to lack of activity

2025-05-24 10:14 UTC, closed without merging